/*
 * remote_config.h
 *
 * Created: 4/15/2023 3:49:19 PM
 *  Author: Hesham Hany
 */ 


#ifndef REMOTE_CONFIG_H_
#define REMOTE_CONFIG_H_

#define UART_COMMUNICATION_INTERFACE  PROTEUS_VIRTUAL_TERMINAL
#define HC_05_BLUETOOTH_MODULE      0
#define PROTEUS_VIRTUAL_TERMINAL    1

#define PROTEUS_VIRTUAL_TERMINAL_STRING_DELIMITER    '\r'
#define HC_05_BLUETOOTH_MODULE_STRING_DELIMITER    '\0'

#endif /* REMOTE_CONFIG_H_ */